### ISSUE TITLE
error in stickbot_bipedal_12dof

### ISSUE THREAD

**Issue by tangt4001** [liangfok/controlit#1]
Hi,there!
I followed the instruction here.http://robotcontrolit.com/tutorials/stickbot_bipedal_12dof/controlit/compos.
when I tried to activated the controller follow the command below, 

`roslaunch atlas_legs_plain_controlit start_controlit.launch`

error was thrown out like **this**:

[ WARN] [1433175985.130841888]:  [00:26:25] [package: controlit_core] [file: ParameterReflection.cpp] [function: lookupParameter] [line: 191]: Could not find parameter 'converged'

**[ERROR] [1433175985.132517001]:  [00:26:25] [package: controlit_core] [file: Coordinator.cpp] [function: init] [line: 164]: Exception thrown during initialization: yaml-cpp: error at line 198, column 7: key not found: parameter**

controlit_exec: /home/tb/controlit_workspace/src/controlit/controlit_core/src/Coordinator.cpp:165: bool controlit::Coordinator::init(): Assertion `false' failed.
[stickbot_bipedal_12dof_controller/controlit_exec-1] process has died [pid 26653, exit code -6, cmd /home/tb/controlit_workspace/devel/lib/controlit_exec/controlit_exec __name:=controlit_exec __log:=/home/tb/.ros/log/bfa20d9e-0871-11e5-ba2f-74e50b88ced0/stickbot_bipedal_12dof_controller-controlit_exec-1.log].
log file: /home/tb/.ros/log/bfa20d9e-0871-11e5-ba2f-74e50b88ced0/stickbot_bipedal_12dof_controller-controlit_exec-1*.log

**Comment by liangfok** [comment]
Thanks for the note. I fixed the stickbot_bipedal_12dof demo by removing the binding specifications from the YAML files:

https://github.com/liangfok/controlit_configs/commit/e2f133f41fadca7f5c1dab4776f144330f70b3bb

Please update your clone of controlit_configs and try again:

```
$ roscd controlit_configs
$ git pull origin master
```

**Comment by liangfok** [comment]
It looks like you were also trying to run the atlas_legs_plain_controlit demo. I fixed the YAML configuration files in that demo in the following commit: https://github.com/liangfok/controlit_configs/commit/9ac038d4b377ed29a7330cbff5b41f932cbdd12c

Again, update your clone of controlit_configs and see if the error persists.

```
$ roscd controlit_configs
$ git pull origin master
```

**Comment by tangt4001** [comment]
It works! You have fixed the issue. So, I think we could close it now.
