### ISSUE TITLE
Automatically Test Every ControlIt! Demo

### ISSUE THREAD

**Issue by tangt4001** [liangfok/controlit#4]
**It seems that automatically test mechanism is not working properly. error is thrown out like this:**

tb@tb:~/controlit_workspace/src/controlit/controlit_quality_assurance$ rosrun controlit_quality_assurance groupTest.py 

Started with the following arguments:
- haharobotPath:  
- timeOut:         20
- errorThreshold:  0.05
- stdOut :         True
- stdErr:          True

Traceback (most recent call last):
  File "/home/tb/controlit_workspace/src/controlit/controlit_quality_assurance/scripts/groupTest.py", line 381, in <module>
    with open(yaml_path, 'r') as testing_list_yaml:
IOError: [Errno 2] No such file or directory: '/controlit/controlit_quality_assurance/scripts/testing_list.yaml'

**Comment by tangt4001** [comment]
in the file of groupTest.py, at the line of 291.
ROS_WORKSPACE is not allocated before, 

`$ export ROS_WORKSPACE=/home/[username]/controlit_workspace/src`

**Comment by liangfok** [comment]
Thanks for posting this issue. I will look into it after resolving some of the other issues.
