### ISSUE TITLE
How to Use Controlit! with stickbot_bipedal_12dof (COM Position)

### ISSUE THREAD

**Issue by tangt4001** [liangfok/controlit#5]
in the tutorial, we are expecting to move the position of COM with below command:

`$ rostopic pub --once /stickbot_bipedal_12dof_controller/COMTask/goalPosition std_msgs/Float64MultiArray '{layout: {dim: [{label: "x", size: 3, stride: 3}], data_offset: 0}, data: [0, -0.3, 0.1]}'`

however, there is no **/stickbot_bipedal_12dof_controller/COMTask/goalPosition** topic generated, in other words, we could not control the COM.

I think there is something wrong in COMControl.yaml.

**Comment by liangfok** [comment]
Thanks for pointing out this problem. It is caused by the fact that the default parameter bindings aren't defined in COMTask. I will add the default bindings soon.

**Comment by tangt4001** [comment]
yes, you are right. I modified the COMTask.cpp, and add an addDefaultbindings() function which is similar to the one in JointPositionTask.cpp.

**Comment by liangfok** [comment]
I added the default bindings to COMTask.cpp in the following commit: https://github.com/liangfok/controlit/commit/cbc711e62169be70c79c5190b8422a4a9cc91b02

Please update your clone of controlit:

```
$ roscd controlit
$ git pull origin master
```

I think default parameter bindings could be cleaned up and automatically created by defining the parameter's direction upon declaration. The following issue shall track this potential improvement: https://github.com/liangfok/controlit/issues/6

**Comment by tangt4001** [comment]
Agree! In some circumstances, both com control and jointpos control are needed at the same time. it would be necessary to reconsider this issue, you are right, and I think we should close this issue now.
